image: alpine:latest

before_script:
  - apk --no-cache add cmake make boost boost-dev gcc g++

stages:
  - build

Build:
  stage: build
  script:
    - make
  only:
    - master
  tags:
    - mmai
  artifacts:
    paths:
      - ./
